### PR TITLE
Support for Sony Bravia logo

### PR DESCRIPTION
**Pull request by iAmMrinal0**
Sony Bravia devices display default logo, added a new logo and displays it when a Sony Bravia device is used.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Please remove the newline at the end of the file, this will break the `img.php` proxy.

**Comment by iAmMrinal0** [comment]
Sorry about the delay. Seems git added new lines as .gitattributes did not have info about line normalization. Closing this issue and sending it again.

**Comment by Arcanemagus** [comment]
Although that sounds like an excellent idea to set up to configure the default line endings for the project, I can't find any documentation on how that would help prevent a blank line from being inserted at the end of the critical files.

Can you enlighten me on how that would be accomplished?

**Comment by iAmMrinal0** [comment]
I have been trying to do that but can't get it to work. And curious, why prevent line breaks? I have been reading that it was standard to add them.

**Comment by Arcanemagus** [comment]
The PHP interpreter echos everything outside the `<?php ?>` tags, having a new line at the end of the files causes it to echo the newline into the contents of the picture when we are in the image proxy script. This includes any file that run when running the proxy. This means that `functions.php`, `ConfigClass.php` and `img.php` can't have _any_ content outside the `<?php ?>` tags or the images proxied from the Plex server are broken.

**Comment by iAmMrinal0** [comment]
Okay. I didn't notice that at first. Thanks for clearing it up.

**Comment by Arcanemagus** [comment]
No problem :wink:.

**Comment by timrettop** [comment]
@iAmMrinal0 I'm not sure if you are a VIM user or not, but I found this vim script handy: 

http://www.vim.org/scripts/script.php?script_id=4550

**Pull request closed without merging**
