### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by olimortimer**
Gitignore for .htaccess, .htpasswd and config/config.php files

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Thanks! I kept meaning to do this but kept getting interrupted with code :stuck_out_tongue:.

**Comment by Arcanemagus** [comment]
Okay... really need to watch the branch before merging things. For now I guess that will have to stay since reverting it will just be more commits to master and it doesn't harm anything.

**Comment by olimortimer** [comment]
Did you want it into the dev branch instead?

**Comment by Arcanemagus** [comment]
Yea, the dev branch is massively ahead of the master branch, when we have 1.7.0 ready we will be (finally) bringing master up to date. I think I can just merge this commit into the dev branch and call it good though.

Usually when a project has a dev branch they like PR's to be submitted against that, allowing testing before being pushed to the master branch. As I said before this commit has no effect on the actual project so I don't think it's an issue leaving it in master.

**Pull request merged**
