### PR TITLE
Settings Rewrite

### PR DESCRIPTION
**Pull request by Arcanemagus**
Changes the settings file to be saved in the JSON format.
When saving new settings the values are verified to be correct instead of being directly written to the drive.
Reading of the settings is cached for up to 60s in a session to speed up access.

Implements https://github.com/ecleese/plexWatchWeb/issues/127.

### CODE REVIEW

**Comment by timrettop** [comment]
@Arcanemagus I was looking at this PR, and merged it into my fork to see it in action, and with my existing config.php, the index page only loads partially with a bunch of 500 errors, and other pages do not load.   

You might want to have a converter function, or have the users re-enter settings, depending on what you think is right.

**Comment by Arcanemagus** [comment]
There _is_ a converter function, which worked on my settings files from the current dev branch. Can you post the errors you are seeing so I can put in checks/fixes for them in there?

**Comment by Arcanemagus** [comment]
Just an FYI: Currently this breaks _somewhat_ gracefully if the Plex token is de-authorized out from underneath it, but needs a lot of work in that aspect still before I feel comfortable merging this in.

**Comment by Arcanemagus** [comment]
It appears that the Time and Date formats are getting a new-line pushed in there somehow, as soon as that gets fixed I think this is ready for merging.

@timrettop Can you please try out the current state and see if you are having errors importing your settings? That is probably the aspect that will potentially have the most issues so any input is greatly appreciated.

**Comment by timrettop** [comment]
@arcanemagus I should be able to give this a whirl tonight, I'll let you know!

**Comment by Arcanemagus** [comment]
@timrettop Looks like since I last tested it and now it broke reading the original settings, getting that working properly again right now :wink:.

**Comment by Arcanemagus** [comment]
@timrettop That should work for you! When you first load this with an older style settings file it will process it into the new format (verifying values as it does so), and then overwrite the settings file to the new style.

At this point I can't get it to break (into an unrecoverable state) so I'll be merging this in in the morning unless I hear that there are further issues with it first.

**Pull request merged**
